<a href="https://colab.research.google.com/github/SHAIMA-HAQUE/Diabetes-Prediction/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [131]:
import numpy as np
import pandas as pd

In [132]:
dataset = pd.read_csv('diabetes_data_upload.csv')
print(dataset)

     Age  Gender Polyuria  ... Alopecia Obesity     class
0     40    Male       No  ...      Yes     Yes  Positive
1     58    Male       No  ...      Yes      No  Positive
2     41    Male      Yes  ...      Yes      No  Positive
3     45    Male       No  ...       No      No  Positive
4     60    Male      Yes  ...      Yes     Yes  Positive
..   ...     ...      ...  ...      ...     ...       ...
515   39  Female      Yes  ...       No      No  Positive
516   48  Female      Yes  ...       No      No  Positive
517   58  Female      Yes  ...       No     Yes  Positive
518   32  Female       No  ...      Yes      No  Negative
519   42    Male       No  ...       No      No  Negative

[520 rows x 17 columns]


In [133]:
dataset['class'].value_counts()


Positive    320
Negative    200
Name: class, dtype: int64

In [134]:
dataset.isna().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

In [141]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for i in dataset.columns[1:] :
    dataset[i] = le.fit_transform(dataset[i])

In [142]:
X = dataset.drop(['class'], axis="columns")
X.head()

Age  Gender  Polyuria  ...  muscle stiffness  Alopecia  Obesity
0   40       1         0  ...                 1         1        1
1   58       1         0  ...                 0         1        0
2   41       1         1  ...                 1         1        0
3   45       1         0  ...                 0         0        0
4   60       1         1  ...                 1         1        1

[5 rows x 16 columns]

In [143]:
Y = dataset['class']
Y.head()

0    1
1    1
2    1
3    1
4    1
Name: class, dtype: int64

In [144]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for feature in objectList:
    X[feature] = le.fit_transform(X[feature].astype(str))

print (X.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    int64
 2   Polyuria            520 non-null    int64
 3   Polydipsia          520 non-null    int64
 4   sudden weight loss  520 non-null    int64
 5   weakness            520 non-null    int64
 6   Polyphagia          520 non-null    int64
 7   Genital thrush      520 non-null    int64
 8   visual blurring     520 non-null    int64
 9   Itching             520 non-null    int64
 10  Irritability        520 non-null    int64
 11  delayed healing     520 non-null    int64
 12  partial paresis     520 non-null    int64
 13  muscle stiffness    520 non-null    int64
 14  Alopecia            520 non-null    int64
 15  Obesity             520 non-null    int64
dtypes: int64(16)
memory usage: 65.1 KB
None


In [145]:
X.head(5)

Age  Gender  Polyuria  ...  muscle stiffness  Alopecia  Obesity
0   40       1         0  ...                 1         1        1
1   58       1         0  ...                 0         1        0
2   41       1         1  ...                 1         1        0
3   45       1         0  ...                 0         0        0
4   60       1         1  ...                 1         1        1

[5 rows x 16 columns]

In [146]:
print(X.shape, Y.shape)

(520, 16) (520,)


In [156]:
X.corrwith(y)

Age                   0.108679
Gender               -0.449233
Polyuria              0.665922
Polydipsia            0.648734
sudden weight loss    0.436568
weakness              0.243275
Polyphagia            0.342504
Genital thrush        0.110288
visual blurring       0.251300
Itching              -0.013384
Irritability          0.299467
delayed healing       0.046980
partial paresis       0.432288
muscle stiffness      0.122474
Alopecia             -0.267512
Obesity               0.072173
dtype: float64

In [147]:
X_FS = X[['Polyuria', 'Polydipsia','Age', 'Gender','partial paresis','sudden weight loss','Irritability', 'delayed healing','Alopecia','Itching']]

In [148]:
print(Y)

0      1
1      1
2      1
3      1
4      1
      ..
515    1
516    1
517    1
518    0
519    0
Name: class, Length: 520, dtype: int64


In [149]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_FS, Y, test_size = 0.2,random_state=12345,shuffle=True)
print(X_train.shape, X_test.shape)

(416, 10) (104, 10)


In [150]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression(random_state = 0, penalty = 'l2')
logReg.fit(X_train, Y_train)

Y_pred = logReg.predict(X_test)
print(Y_test, Y_pred)

148    1
190    1
445    1
52     1
183    1
      ..
100    1
391    0
363    1
408    0
240    0
Name: class, Length: 104, dtype: int64 [1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 0 0 0 1 0 0 1 1 1 0 0 0 1 1 1 1 1 1
 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0
 0 1 1 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 0 1 0 0 1 0 1 0 0]


In [151]:
from sklearn.metrics import  confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred)) 
print("Precision:\n", precision_score(Y_test, Y_pred, average=None))
print("Recall:\n", recall_score(Y_test, Y_pred, average = None))

Confusion Matrix:
 [[33  3]
 [ 6 62]]
Accuracy:
 0.9134615384615384
Precision:
 [0.84615385 0.95384615]
Recall:
 [0.91666667 0.91176471]


In [153]:
#KNN Classifier

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_knn))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_knn)) 

Confusion Matrix:
 [[34  2]
 [17 51]]
Accuracy:
 0.8173076923076923


In [154]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

Y_pred_dtc = dtc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_dtc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_dtc))

Confusion Matrix:
 [[34  2]
 [ 5 63]]
Accuracy:
 0.9326923076923077


In [155]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)

Y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rfc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rfc))

Confusion Matrix:
 [[36  0]
 [ 2 66]]
Accuracy:
 0.9807692307692307
